-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS ded."hub books"
(
    book_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    book_name character varying(100) NOT NULL,
    PRIMARY KEY (book_id)
);

CREATE TABLE IF NOT EXISTS ded."hub clients"
(
    client_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    client_name character varying(100) NOT NULL,
    PRIMARY KEY (client_id)
);

CREATE TABLE IF NOT EXISTS ded."hub seller"
(
    seller_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    seller_name character varying NOT NULL,
    PRIMARY KEY (seller_id)
);

CREATE TABLE IF NOT EXISTS ded."hub author"
(
    author_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    author_name character varying(100) NOT NULL,
    PRIMARY KEY (author_id)
);

CREATE TABLE IF NOT EXISTS ded."link deal"
(
    deal_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    "seller_Id" integer NOT NULL,
    book_id integer NOT NULL,
    client_id integer NOT NULL,
    author_id integer NOT NULL,
    PRIMARY KEY (deal_id)
);

CREATE TABLE IF NOT EXISTS ded.books_author_link
(
    books_book_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    author_author_id integer NOT NULL GENERATED ALWAYS AS IDENTITY
);

CREATE TABLE IF NOT EXISTS ded."seller_clients link"
(
    seller_seller_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    clients_client_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    deal_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    PRIMARY KEY (deal_id)
);

CREATE TABLE IF NOT EXISTS books.sattelite_deal
(
    deal_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    date date NOT NULL,
    quantiti integer NOT NULL,
    PRIMARY KEY (deal_id)
);

CREATE TABLE IF NOT EXISTS ded."sat client"
(
    "client id" integer NOT NULL,
    client_phone_num numeric(15) NOT NULL,
    client_adress character varying(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ded."sat books "
(
    book_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    book_year date NOT NULL,
    book_country character varying(100) NOT NULL,
    PRIMARY KEY (book_id)
);

CREATE TABLE IF NOT EXISTS ded."sat author"
(
    author_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    author_birdth date NOT NULL,
    authore_male character varying(20) NOT NULL,
    PRIMARY KEY (author_id)
);

CREATE TABLE IF NOT EXISTS ded."sat seller"
(
    seller_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    seller_experience numeric NOT NULL,
    seller_birdth date NOT NULL,
    PRIMARY KEY (seller_id)
);

ALTER TABLE IF EXISTS ded."hub books"
    ADD FOREIGN KEY (book_id)
    REFERENCES ded."sat books " (book_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS ded."hub seller"
    ADD FOREIGN KEY (seller_id)
    REFERENCES ded."sat seller" (seller_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS ded."hub author"
    ADD FOREIGN KEY (author_id)
    REFERENCES ded."sat author" (author_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS ded."link deal"
    ADD FOREIGN KEY ("seller_Id")
    REFERENCES ded."hub seller" (seller_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS ded."link deal"
    ADD FOREIGN KEY (book_id)
    REFERENCES ded."hub books" (book_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS ded."link deal"
    ADD FOREIGN KEY (client_id)
    REFERENCES ded."hub clients" (client_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS ded."link deal"
    ADD FOREIGN KEY (author_id)
    REFERENCES ded."hub author" (author_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS ded.books_author_link
    ADD FOREIGN KEY (books_book_id)
    REFERENCES ded."hub books" (book_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS ded.books_author_link
    ADD FOREIGN KEY (author_author_id)
    REFERENCES ded."hub author" (author_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS ded."seller_clients link"
    ADD FOREIGN KEY (seller_seller_id)
    REFERENCES ded."hub seller" (seller_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS ded."seller_clients link"
    ADD FOREIGN KEY (clients_client_id)
    REFERENCES ded."hub clients" (client_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS books.sattelite_deal
    ADD FOREIGN KEY (deal_id)
    REFERENCES ded."link deal" (deal_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS ded."sat client"
    ADD FOREIGN KEY ("client id")
    REFERENCES ded."hub clients" (client_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
